### ISSUE TITLE
Add to calendar does not add location, if present

### ISSUE THREAD

**Issue by almereyda** [angusmcleod/discourse-events#1]
When adding an event to a calendar, it would be nice if the location would be included, if present by the other plugin.

**Comment by angusmcleod** [comment]
@almereyda Yes, thanks for the note. I'll fix this tomorrow.

**Comment by angusmcleod** [comment]
@almereyda Fixed: https://github.com/angusmcleod/discourse-events/commit/e7b40beeedd1fca366c3807398fef6381b4e1185
