### ISSUE TITLE
events_event_label_short_format not working for events with timezones

### ISSUE THREAD

**Issue by yanokwa** [angusmcleod/discourse-events#21]
I'm using b72bc24 of the plugin on Discourse v2.0.0.beta7 and events_event_label_short_format not working for events with timezones.

**Settings**
<img width="739" alt="screen shot 2018-04-25 at 12 34 15" src="https://user-images.githubusercontent.com/32369/39268568-159e454a-4885-11e8-9bd0-3121ba660687.png">

**Topic list**
<img width="625" alt="screen shot 2018-04-25 at 12 34 23" src="https://user-images.githubusercontent.com/32369/39268569-15b8b614-4885-11e8-8644-298aa4e01a6e.png">

I would expect the topic list would not have any timezone information or would allow me to format it.

**Comment by angusmcleod** [comment]
Can you tell me a bit more:

- Does the event in the example have a custom timezone set? (and if so what is it?)

- Do you have a default timezone set for the site? (and if so what is it?)

The current logic on whether or not to display a timezone is:

>  if the event is not an all day event and has a custom timezone that is different from the standard timezone (either the site setting or the user’s own timezone), then the timezone is displayed.

[See further.](https://meta.discourse.org/t/events-plugin-calendar/69776/224?u=angus).

Before I make any further changes, I want to be sure that logic is working.

**Comment by yanokwa** [comment]
The two events shown in my above example are not all day events and they have a custom timezone set. The April 24th event was GMT+00:00 UTC, the April 18th event was GMT+00:00 London. The same issue occurs with an event we have set with GMT+01:00 West Central Africa. We currently do not have a default time zone set on the server.

My hope is that when a timezone is going to be displayed, the event label format will let me customize that timezone text. And it's fine if the timezone is always shown even if it's not set, I just want to be able to tweak how it looks 😀

**Comment by angusmcleod** [comment]
Timezone formatting is now added. See further here:

https://meta.discourse.org/t/events-plugin-calendar/69776/270?u=angus
