### ISSUE TITLE
Add event date after topic creation

### ISSUE THREAD

**Issue by jazongb** [angusmcleod/discourse-events#24]
I have a user who created an event, but didn't add in the date/time during creation, consequently, it just appears as any other topic. Is it possible to add this information after the topic is created, so that it appears correctly as an event in Discourse?

**Comment by angusmcleod** [comment]
Hey @jazongb. Yes, if you edit the first post of the topic you'll see controls to add an event to the topic. 

<img width="175" alt="screenshot at may 30 09-03-56" src="https://user-images.githubusercontent.com/5931623/40690035-69abaca8-63e8-11e8-8399-6270986dc9c0.png">
