### ISSUE TITLE
Local datetime format support?

### ISSUE THREAD

**Issue by Amethi** [angusmcleod/discourse-events#28]
Thanks for the plugin!

Any chance we could get it to support the locale that Discourse is configured to use? I use it in the UK and it's showing date formats (on category pages) in what I assume is US format, which is very confusing for our users.

**Comment by angusmcleod** [comment]
Hey @Amethi,

You can configure the format of dates using the events site settings. Search for 'events' in your Discourse site settings and you'll see all the different options.

**Comment by Amethi** [comment]
Awesome, thanks!
