### ISSUE TITLE
Private iCal feed

### ISSUE THREAD

**Issue by angusmcleod** [angusmcleod/discourse-events#29]
An iCal feed authenticated via User API keys for private forums or private categories
- https://meta.discourse.org/t/events-plugin-calendar/69776/366?u=angus

**Comment by xenDE** [comment]
yep, thats a show stopper for me ;(

**Comment by angusmcleod** [comment]
The plugin actually supports this now.

Add an api_key and api_username to a calendar feed and it’ll work in a private category

**Comment by xenDE** [comment]
Hi,

i have no api_key in the generated links:

![grafik](https://user-images.githubusercontent.com/2836430/62821596-a9748980-bb77-11e9-9191-1db65b49832b.png)

and i can not find a way in the config for "generate calendar subscribe links with api-key"

I think it would be better if the plugin would create a user api-key which is listed in the user-config under "Apps" as calendar api-key and then use it.

or i'm wrong here?

best regards and thanks for the great plugin!

**Comment by angusmcleod** [comment]
@xenDE Yes, you currently have to add the key and username manually. Would you be able to submit a feature request for automatically adding the api_key and api_username to iCal links in private categories? 

https://thepavilion.io/w/feature-request

Having a clearly expressed feature request will help me and other folks who are helping to maintain this plugin schedule it in to our workflow. Thanks.
