### ISSUE TITLE
Only allow some users to create events 

### ISSUE THREAD

**Issue by yanokwa** [angusmcleod/discourse-events#48]
We have an issue where very new users to our community are accidentally creating events. Or rather, they post in a category that has events enabled and add a date time because they thing that is somehow a required field. Then mods have to delete the datetime, then move the topic to the correct category.

If we could restrict the number of people who could create events (e.g., based on a Discourse group) this would make life a lot easier for us.

**Comment by angusmcleod** [comment]
Hey @yanokwa, there are existing site and category settings for minimum trust levels to create an event. Does this address the issue?

<img width="493" alt="Screen Shot 2019-03-12 at 6 01 52 PM" src="https://user-images.githubusercontent.com/5931623/54180965-1adcdd00-44f1-11e9-8128-8f962993611b.png">

**Comment by yanokwa** [comment]
Ugh, can't believe I didn't see that. Yes, that'll work great.
