### ISSUE TITLE
Feature Request: Allow admins to RSVP on behalf of other users & remove users from the RSVP list

### ISSUE THREAD

**Issue by jaydrogers** [angusmcleod/discourse-events#49]
# Background
* I use Discourse Events to organize all of our in person meetups
* I send out an email to the entire group using Mailchimp to promote the event
* Some people will actually use the RSVP function, others might say that they can make it to me in person

# Problem
* This makes the RSVP count look "low" on the event when there are actually a lot more people attending
* Sometimes people who originally RSVP to the event have a change in plans. Most of the time they prefer to call and explain why they cannot make it, rather than posting in Discourse
* I now have to manage a separate list of people who RSVP via Discourse and who RSVP to me through other mediums

# Proposed solution
Allow admins to "edit" the RSVP list. This means:
* Admins can remove users from the RSVP list
* Admins can add users to the RSVP list

Thanks for all of your great work @angusmcleod! You have built an amazing product!!

**Comment by angusmcleod** [comment]
Hey Jay, thanks for this detailed write-up! Yes, I'm in favour of the idea. I've slotted in some time in May to take a look at implementing this: https://discourse.angusmcleod.com.au/t/discourse-events-add-admin-controls-for-rsvp-list/840.

**Comment by jaydrogers** [comment]
Thank you so much @angusmcleod! You do amazing work!!

**Comment by angusmcleod** [comment]
@jaydrogers I've just committed this feature: https://github.com/angusmcleod/discourse-events/commit/cc18855c1227d35a6e2cd7c2d22db6304db47c14

There's now a user-selector in the "Add Event" modal that allows you to add and remove users from the RSVP list.

<img width="293" alt="Screen Shot 2019-05-01 at 4 10 47 PM" src="https://user-images.githubusercontent.com/5931623/57007399-b5bd8200-6c2b-11e9-8270-3288951344a2.png">

**Comment by jaydrogers** [comment]
This is amazing! Thank you so much @angusmcleod!! Where can we buy you a coffee or a beer as a thank you?

**Comment by angusmcleod** [comment]
Thanks @jaydrogers :) I do take small donations [here](https://discourse.angusmcleod.com.au/donate), but totally optional!
