### ISSUE TITLE
End date not displayed when same day as start date but different month

### ISSUE THREAD

**Issue by hidrarga** [angusmcleod/discourse-events#50]
Thanks for this plugin, I find it really useful :) 

I spotted a small bug when I create an event where the end date is exactly one month after the start date (i.e only the month is changed, but the day stays the same). The end date isn't displayed at all (see screenshot). However, the end date is correctly stored, since I see that everything is fine in the calendar, for instance.

On this screenshot, I set up an event from 8th April to 8th May, but as you can see only the start date is displayed : 
![image](https://user-images.githubusercontent.com/2971096/56840261-e9448900-6886-11e9-81d8-811f067c1306.png)

The bug appears both on the list of topics and in the topic itself.

**Comment by angusmcleod** [comment]
Thanks, added to the agenda here: https://discourse.angusmcleod.com.au/t/events-end-date-bug/915

**Comment by angusmcleod** [comment]
This is now fixed: https://github.com/angusmcleod/discourse-events/commit/9e30f32a8b47f843685a85c42ff03fcfe9cf9628
