### ISSUE TITLE
Email notifications no longer work

### ISSUE THREAD

**Issue by tbrisker** [angusmcleod/discourse-events#57]
Looks like a recent change in discourse (possibly  https://github.com/discourse/discourse/pull/7934/ ?) causes mail notifications to break when the plugin is installed. The stack trace and further information can be found at https://meta.discourse.org/t/email-jobs-failing-after-updating-to-latest/125066
I tried looking into the code and found nothing obvious that would cause this, but unfortunately I'm not familiar enough with discourse internals to be able to properly debug it.

**Comment by xenDE** [comment]
same here, no mail notfications working in discourse.
need to disable the plugin.

**Comment by angusmcleod** [comment]
@tbrisker @xenDE Thanks guys. I'll be taking a look at this today.

**Comment by angusmcleod** [comment]
@xenDE @tbrisker This is resolved: https://thepavilion.io/t/events-email-jobs-failing/1423/4

**Comment by xenDE** [comment]
Its back working!

Thank you for your quick reaction.
